plugins {
    id("packetentities.java-library")
    id("packetentities.publishing")
    alias(libs.plugins.shadow)
    alias(libs.plugins.blossom)
}

sourceSets.main {
    java {
        srcDir(file("src/autogenerated/java"))
    }
    blossom {
        javaSources {
            property("COMMIT", System.getenv("GITHUB_SHA") ?: "LOCAL")
            property("BRANCH", System.getenv("GITHUB_REF") ?: "LOCAL")
            property("GROUP", project.group.toString())
            property("ARTIFACT", project.name)
            property("VERSION", project.version.toString())
        }
    }
}

dependencies {
    compileOnly(libs.adventure.api)
    compileOnly(libs.packetevents.api)
    implementation(libs.fastutil)
}

tasks {
    shadowJar {
        archiveClassifier.set("")
        minimize()

        relocate("it.unimi.dsi.fastutil", "${project.group}.api.fastutil")
    }

    javadoc {
        val options = options as StandardJavadocDocletOptions
        options.use(true)
        options.tags("mcversions:A:Minecraft Versions:")
        options.tags("mcwiki:Minecraft.wiki:")
        options.tags("view:Entity Meta Field View:")
    }
}
