plugins {
    id("packetentities.java-library")
    id("packetentities.publishing")
    alias(libs.plugins.shadow)
}

sourceSets.main {
    java {
        srcDir(file("src/autogenerated/java"))
    }
}

dependencies {
    compileOnly(libs.adventure.api)
    compileOnly(libs.packetevents.api)
    implementation(libs.fastutil)
}

tasks {
    shadowJar {
        archiveClassifier.set("")
        minimize()

        relocate("it.unimi.dsi.fastutil", "${project.group}.api.fastutil")
    }
}
