plugins {
    id("packetentities.java-library")
    application
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("dev.threeadd.packetentities.codegen.MetaPropertiesCodeGen")
}

repositories {
    mavenCentral()

    maven("https://repo.viaversion.com")
}

dependencies {
    annotationProcessor(libs.jetbrains.annotations)
    implementation(libs.packetevents.api)
    implementation(libs.adventure.api)
    implementation(libs.gson)
    implementation(libs.javapoet)
    implementation(libs.jetbrains.annotations)
}

tasks {
    named<JavaExec>("run") {
        mainClass.set("dev.threeadd.packetentities.codegen.MetaPropertiesCodeGen")
        args("$rootDir/src/autogenerated/java")
    }
}
